raw_snapshot_dir: data/raw/latest
curated_dir: data/curated/latest
features_dir: data/features/latest
artifacts_dir: artifacts
sample_submission_stage2: data/raw/latest/SampleSubmissionStage2.csv

seasons:
  min_train_season: 2003
  max_train_season: 2025
  predict_season: 2026

genders:
  - M
  - W
